language: r
sudo: false
cache: packages

r-github-packages:
  - hadley/ggplot2
  - jimhester/covr


after_success:
    - tar -C .. -xf $PKG_TARBALL
    - travis_wait Rscript -e 'covr::coveralls(line_exclusions= c("/src/include/models.hpp", "src/*.cpp", "R/zzz.R", "R/runshiny.R"))'
